#ifndef TEMP_CONSTNUM_H
#define TEMP_CONSTNUM_H

const int WINDOWS_POSITION_X = 50, WINDOWS_POSITION_Y = 100;
const int WINDOWS_SIZE_X = 1000, WINDOWS_SIZE_Y = 1000;
const int N = 100, M = 100;

#endif
